name = "contact-form-app"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/worker"

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"