name = "ergodicityadvantage-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = ".open-next/assets"

# Required for Next.js server-side rendering
compatibility_flags = ["nodejs_compat"]

# Environment variables (available at runtime and build time)
[vars]
NEXT_PUBLIC_SITE_URL = "https://mostlyoptimal.com"