name = "ergodicityadvantage"
compatibility_date = "2024-12-01"

# For Cloudflare Pages with static export
pages_build_output_dir = "./out"

# Environment variables
[vars]
ENVIRONMENT = "production"

# Build configuration
[build]
command = "npm run build"

[build.upload]
format = "service-worker"