name = "ergodicityadvantage-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "out"

# Build configuration
[build]
command = "npm run build"

# Environment variables
[vars]
NEXT_PUBLIC_SITE_URL = "https://mostlyoptimal.com"